-- MySQL Script generated by MySQL Workbench
-- Thu Nov 23 09:42:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profession`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profession` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profession` (
  `profession_id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`profession_id`),
  UNIQUE INDEX `professionid_UNIQUE` (`profession_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`class` ;

CREATE TABLE IF NOT EXISTS `mydb`.`class` (
  `class_id` INT NOT NULL,
  `grade` INT NOT NULL,
  `profession_profession_id` INT NOT NULL,
  PRIMARY KEY (`class_id`),
  UNIQUE INDEX `class_id_UNIQUE` (`class_id` ASC),
  INDEX `fk_class_profession1_idx` (`profession_profession_id` ASC),
  CONSTRAINT `fk_class_profession1`
    FOREIGN KEY (`profession_profession_id`)
    REFERENCES `mydb`.`profession` (`profession_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `sex` CHAR NULL,
  `birthday` INT NULL,
  `class_class_id` INT NOT NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `student_id_UNIQUE` (`student_id` ASC),
  INDEX `fk_student_class_idx` (`class_class_id` ASC),
  CONSTRAINT `fk_student_class`
    FOREIGN KEY (`class_class_id`)
    REFERENCES `mydb`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teacher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `teacher_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `course_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `credit` INT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transcript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transcript` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transcript` (
  `result` INT NULL,
  `second_result` INT NULL DEFAULT -1,
  `student_student_id` INT NOT NULL,
  `course_course_id` INT NOT NULL,
  INDEX `fk_transcript_student1_idx` (`student_student_id` ASC),
  INDEX `fk_transcript_course1_idx` (`course_course_id` ASC),
  PRIMARY KEY (`student_student_id`, `course_course_id`),
  CONSTRAINT `fk_transcript_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transcript_course1`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`plan` (
  `semester` INT NULL,
  `compulsory` TINYINT NULL DEFAULT NULL,
  `course_course_id` INT NOT NULL,
  `profession_profession_id` INT NOT NULL,
  INDEX `fk_plan_course1_idx` (`course_course_id` ASC),
  INDEX `fk_plan_profession1_idx` (`profession_profession_id` ASC),
  PRIMARY KEY (`course_course_id`, `profession_profession_id`),
  CONSTRAINT `fk_plan_course1`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_profession1`
    FOREIGN KEY (`profession_profession_id`)
    REFERENCES `mydb`.`profession` (`profession_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`arrangement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`arrangement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`arrangement` (
  `class_class_id` INT NOT NULL,
  `teacher_teacher_id` INT NOT NULL,
  `course_course_id` INT NOT NULL,
  INDEX `fk_schedule_class1_idx` (`class_class_id` ASC),
  INDEX `fk_schedule_teacher1_idx` (`teacher_teacher_id` ASC),
  INDEX `fk_schedule_course1_idx` (`course_course_id` ASC),
  PRIMARY KEY (`class_class_id`, `teacher_teacher_id`, `course_course_id`),
  CONSTRAINT `fk_schedule_class1`
    FOREIGN KEY (`class_class_id`)
    REFERENCES `mydb`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_teacher1`
    FOREIGN KEY (`teacher_teacher_id`)
    REFERENCES `mydb`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_course1`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
